#!/usr/bin/env bash
# This script installs and configures HAproxy as a load balancer

# Install HAproxy
apt-get update
apt-get install -y haproxy

# Configure HAproxy to distribute traffic to web-01 and web-02 using round-robin algorithm
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 [5953-web-01]-web-01:80 check
    server web02 [5953-web-02]-web-02:80 check
EOF

# Enable HAproxy to be managed via init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy to apply changes
service haproxy restart
