#!/usr/bin/env bash
# Update package lists and install Nginx
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

# Start nginx service
sudo service nginx start

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership of website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
sudo mv /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak

# Create a new index page with "Holberton School"
echo "<!DOCTYPE html>
<html>
<head>
<title>Welcome to Holberton School</title>
</head>
<body>
<h1>Holberton School</h1>
</body>
</html>" | sudo tee /var/www/html/index.html >/dev/null

# Restart nginx
sudo service nginx restart

# Check if Nginx returns a page containing "Holberton School" at its root
if curl -s localhost | grep -q "Holberton School"; then
    echo -e "\nNginx returns a page containing 'Holberton School' at its root.\n"
else
    echo -e "\nNginx does not return a page containing 'Holberton School' at its root.\n"
fi

